---
- name: Install firewalld
  package: 
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and running
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Ensure that the SSH port is open
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify: reload firewalld
