- name: Make sure SSH server is installed
  package:
    name: openssh-server
    state: present

- name: Ensure sshd service is enabled and running
  service:
    name: ssh
    enabled: yes
    state: started

- name: Copy over the SSHD configuration
  copy:
    src: "{{ role_path }}/files/etc/ssh/sshd_config"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart sshd